### PR TITLE
Add deployment variable for lms - JAPACCOE-2845

### PR DESCRIPTION
**Pull request by ddevadat**
Added the endpoint definition to for lms deployment to support cloud-store-sdk 1.4.6

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by heungheung** [comment]
another one need to uptake ALL the changes in 5.1.0........

**Comment by ddevadat** [comment]
@heungheung merge oci-5.1.0-JAPACCOE-2845-release-5.1.0 ---> oci-5.1.0

Branch: oci-5.1.0-JAPACCOE-2845-release-5.1.0 contains the changes from upstream/release_5.1.0

Once this is done we can follow the other pull request
https://github.com/ocisunbird/sunbird-devops/pull/6
https://github.com/ocisunbird/sunbird-devops/pull/5
https://github.com/ocisunbird/sunbird-devops/pull/8

Idea is to use oci-5.1.0 as the main branch which we will use to merge with upstream/release-5.1.0

**Comment by heungheung** [comment]
file ansible/desktop-faq-upload.yml in all CSP implementation, the  
- chatbot
- discussion ui
- desktop faq
- label   
are using different tags and potentially will use different buckets

are we good to put everything to just one "destination_path"?

shall we adapt what the other doing?

**Comment by ddevadat** [comment]
looking into it

**Review by heungheung — APPROVED** [review]
approved

**Pull request merged**
